/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcas_Standard_ExtCharacter */

#ifndef _Included_jcas_Standard_ExtCharacter
#define _Included_jcas_Standard_ExtCharacter
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
