/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcas_Transient */

#ifndef _Included_jcas_Transient
#define _Included_jcas_Transient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcas_Transient
 * Method:    IsNullObj
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jcas_Transient_IsNullObj
  (JNIEnv *, jobject);

/*
 * Class:     jcas_Transient
 * Method:    FinalizeID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jcas_Transient_FinalizeID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
