/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcas_CasCadeException */

#ifndef _Included_jcas_CasCadeException
#define _Included_jcas_CasCadeException
#ifdef __cplusplus
extern "C" {
#endif
#undef jcas_CasCadeException_serialVersionUID
#define jcas_CasCadeException_serialVersionUID -3042686055658047285i64
#undef jcas_CasCadeException_serialVersionUID
#define jcas_CasCadeException_serialVersionUID -3387516993124229948i64
#undef jcas_CasCadeException_serialVersionUID
#define jcas_CasCadeException_serialVersionUID -7034897190745766939i64
#ifdef __cplusplus
}
#endif
#endif
