/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcas_Locker */

#ifndef _Included_jcas_Locker
#define _Included_jcas_Locker
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
