/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcas_Object */

#ifndef _Included_jcas_Object
#define _Included_jcas_Object
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jcas_Object
 * Method:    DownCast
 * Signature: (Ljcas/Standard_CString;Ljcas/Standard_CString;)Ljcas/Object;
 */
JNIEXPORT jobject JNICALL Java_jcas_Object_DownCast
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
