// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _BOPAlgo_Algo_HeaderFile
#define _BOPAlgo_Algo_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _BOPCol_BaseAllocator_HeaderFile
#include <BOPCol_BaseAllocator.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif


//! provides the root interface for algorithms <br>
class BOPAlgo_Algo  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   virtual  void Perform()  = 0;
  
  Standard_EXPORT     Standard_Integer ErrorStatus() const;
  
  Standard_EXPORT     Standard_Integer WarningStatus() const;
  
  Standard_EXPORT    const BOPCol_BaseAllocator& Allocator() const;





protected:

  
  Standard_EXPORT   BOPAlgo_Algo();
Standard_EXPORT virtual ~BOPAlgo_Algo();
  
  Standard_EXPORT   BOPAlgo_Algo(const BOPCol_BaseAllocator& theAllocator);
  
  Standard_EXPORT   virtual  void CheckData() ;
  
  Standard_EXPORT   virtual  void CheckResult() ;


BOPCol_BaseAllocator myAllocator;
Standard_Integer myErrorStatus;
Standard_Integer myWarningStatus;


private:





};





// other Inline functions and methods (like "C++: function call" methods)


#endif
