// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _BOPDS_PassKeyMapHasher_HeaderFile
#define _BOPDS_PassKeyMapHasher_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class BOPDS_PassKey;



class BOPDS_PassKeyMapHasher  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      static  Standard_Integer HashCode(const BOPDS_PassKey& aPKey,const Standard_Integer Upper) ;
  
      static  Standard_Boolean IsEqual(const BOPDS_PassKey& aPKey1,const BOPDS_PassKey& aPKey2) ;





protected:





private:





};


#include <BOPDS_PassKeyMapHasher.lxx>



// other Inline functions and methods (like "C++: function call" methods)


#endif
