// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_SequenceNodeOfSequenceOfMesh_HeaderFile
#define _ColladaMesh_SequenceNodeOfSequenceOfMesh_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ColladaMesh_SequenceNodeOfSequenceOfMesh_HeaderFile
#include <Handle_ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>
#endif

#ifndef _Handle_ColladaMesh_Mesh_HeaderFile
#include <Handle_ColladaMesh_Mesh.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class ColladaMesh_Mesh;
class ColladaMesh_SequenceOfMesh;



class ColladaMesh_SequenceNodeOfSequenceOfMesh : public TCollection_SeqNode {

public:

  
      ColladaMesh_SequenceNodeOfSequenceOfMesh(const Handle(ColladaMesh_Mesh)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_ColladaMesh_Mesh& Value() const;




  DEFINE_STANDARD_RTTI(ColladaMesh_SequenceNodeOfSequenceOfMesh)

protected:




private: 


Handle_ColladaMesh_Mesh myValue;


};

#define SeqItem Handle_ColladaMesh_Mesh
#define SeqItem_hxx <ColladaMesh_Mesh.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMesh.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
