// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_HeaderFile
#define _ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_HeaderFile
#include <Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#endif

#ifndef _Handle_ColladaMesh_MeshTriangle_HeaderFile
#include <Handle_ColladaMesh_MeshTriangle.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class ColladaMesh_MeshTriangle;
class ColladaMesh_SequenceOfMeshTriangle;



class ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle : public TCollection_SeqNode {

public:

  
      ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle(const Handle(ColladaMesh_MeshTriangle)& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Handle_ColladaMesh_MeshTriangle& Value() const;




  DEFINE_STANDARD_RTTI(ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle)

protected:




private: 


Handle_ColladaMesh_MeshTriangle myValue;


};

#define SeqItem Handle_ColladaMesh_MeshTriangle
#define SeqItem_hxx <ColladaMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshTriangle.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
