// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_SequenceOfMeshDomain_HeaderFile
#define _ColladaMesh_SequenceOfMeshDomain_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_ColladaMesh_MeshDomain_HeaderFile
#include <Handle_ColladaMesh_MeshDomain.hxx>
#endif
#ifndef _Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshDomain_HeaderFile
#include <Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class ColladaMesh_MeshDomain;
class ColladaMesh_SequenceNodeOfSequenceOfMeshDomain;



class ColladaMesh_SequenceOfMeshDomain  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      ColladaMesh_SequenceOfMeshDomain();
  
  Standard_EXPORT     void Clear() ;
~ColladaMesh_SequenceOfMeshDomain()
{
  Clear();
}
  
  Standard_EXPORT    const ColladaMesh_SequenceOfMeshDomain& Assign(const ColladaMesh_SequenceOfMeshDomain& Other) ;
   const ColladaMesh_SequenceOfMeshDomain& operator =(const ColladaMesh_SequenceOfMeshDomain& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(ColladaMesh_MeshDomain)& T) ;
  
        void Append(ColladaMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(ColladaMesh_MeshDomain)& T) ;
  
        void Prepend(ColladaMesh_SequenceOfMeshDomain& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(ColladaMesh_MeshDomain)& T) ;
  
        void InsertBefore(const Standard_Integer Index,ColladaMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(ColladaMesh_MeshDomain)& T) ;
  
        void InsertAfter(const Standard_Integer Index,ColladaMesh_SequenceOfMeshDomain& S) ;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshDomain& First() const;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshDomain& Last() const;
  
        void Split(const Standard_Integer Index,ColladaMesh_SequenceOfMeshDomain& Sub) ;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshDomain& Value(const Standard_Integer Index) const;
   const Handle_ColladaMesh_MeshDomain& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(ColladaMesh_MeshDomain)& I) ;
  
  Standard_EXPORT     Handle_ColladaMesh_MeshDomain& ChangeValue(const Standard_Integer Index) ;
    Handle_ColladaMesh_MeshDomain& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   ColladaMesh_SequenceOfMeshDomain(const ColladaMesh_SequenceOfMeshDomain& Other);




};

#define SeqItem Handle_ColladaMesh_MeshDomain
#define SeqItem_hxx <ColladaMesh_MeshDomain.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshDomain.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
