// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_MeshTriangle_HeaderFile
#define _ColladaMesh_MeshTriangle_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_ColladaMesh_MeshTriangle_HeaderFile
#include <Handle_ColladaMesh_MeshTriangle.hxx>
#endif

#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Real_HeaderFile
#include <Standard_Real.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
class Standard_NegativeValue;


//! A  mesh triangle is defined with <br>
//!          three geometric vertices and an orientation <br>
//! <br>
class ColladaMesh_MeshTriangle : public MMgt_TShared {

public:

  //! empty constructor <br>
  Standard_EXPORT   ColladaMesh_MeshTriangle();
  //! create a triangle defined with the indexes of its three vertices <br>
//!          and its orientation <br>//! Raised if V1, V2 or V3 is lower than zero <br>
  Standard_EXPORT   ColladaMesh_MeshTriangle(const Standard_Integer V1,const Standard_Integer V2,const Standard_Integer V3,const Standard_Real n1x,const Standard_Real n1y,const Standard_Real n1z,const Standard_Real n2x,const Standard_Real n2y,const Standard_Real n2z, const Standard_Real n3x,const Standard_Real n3y,const Standard_Real n3z );
  //! get indexes of the three vertices (V1,V2,V3) and the orientation <br>
  Standard_EXPORT     void GetVertexAndOrientation(Standard_Integer& V1,Standard_Integer& V2,Standard_Integer& V3,Standard_Real& n1x,Standard_Real& n1y,Standard_Real& n1z,Standard_Real& n2x,Standard_Real& n2y,Standard_Real& n2z,Standard_Real& n3x,Standard_Real& n3y,Standard_Real& n3z) const;
  //! set indexes of the three vertices (V1,V2,V3) and the orientation <br>//! Raised if V1, V2 or V3 is lower than zero <br>
  Standard_EXPORT     void SetVertexAndOrientation(const Standard_Integer V1,const Standard_Integer V2,const Standard_Integer V3,const Standard_Real n1x,const Standard_Real n1y,const Standard_Real n1z,const Standard_Real n2x,const Standard_Real n2y,const Standard_Real n2z,const Standard_Real n3x,const Standard_Real n3y,const Standard_Real n3z) ;
  //! get indexes of the three vertices (V1,V2,V3) <br>
  Standard_EXPORT     void GetVertex(Standard_Integer& V1,Standard_Integer& V2,Standard_Integer& V3) const;
  //! set indexes of the three vertices (V1,V2,V3) <br>//! Raised if V1, V2 or V3 is lower than zero <br>
  Standard_EXPORT     void SetVertex(const Standard_Integer V1,const Standard_Integer V2,const Standard_Integer V3) ;




  DEFINE_STANDARD_RTTI(ColladaMesh_MeshTriangle)

protected:




private: 


Standard_Integer MyV1;
Standard_Integer MyV2;
Standard_Integer MyV3;
Standard_Real Myn1x;
Standard_Real Myn1y;
Standard_Real Myn1z;
Standard_Real Myn2x;
Standard_Real Myn2y;
Standard_Real Myn2z;
Standard_Real Myn3x;
Standard_Real Myn3y;
Standard_Real Myn3z;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
