// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_HeaderFile
#define _ColladaMesh_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Handle_ColladaMesh_Mesh_HeaderFile
#include <Handle_ColladaMesh_Mesh.hxx>
#endif
class ColladaMesh_Mesh;
class ColladaMesh_Mesh;
class ColladaMesh_MeshExplorer;
class ColladaMesh_MeshDomain;
class ColladaMesh_MeshTriangle;
class ColladaMesh_SequenceOfMeshDomain;
class ColladaMesh_SequenceOfMeshTriangle;
class ColladaMesh_SequenceOfMesh;
class ColladaMesh_SequenceNodeOfSequenceOfMeshDomain;
class ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle;
class ColladaMesh_SequenceNodeOfSequenceOfMesh;


//! Implements a  basic  mesh data-structure  for  the <br>
//!          needs of the application fast prototyping. <br>
//! <br>
class ColladaMesh  {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  //! Make a merge of two Mesh and returns a new Mesh. <br>
//!          Very useful if you want to merge partMesh and CheckSurfaceMesh <br>
//!          for example <br>
  Standard_EXPORT   static  Handle_ColladaMesh_Mesh Merge(const Handle(ColladaMesh_Mesh)& mesh1,const Handle(ColladaMesh_Mesh)& mesh2) ;





protected:





private:




friend class ColladaMesh_Mesh;
friend class ColladaMesh_MeshExplorer;
friend class ColladaMesh_MeshDomain;
friend class ColladaMesh_MeshTriangle;
friend class ColladaMesh_SequenceOfMeshDomain;
friend class ColladaMesh_SequenceOfMeshTriangle;
friend class ColladaMesh_SequenceOfMesh;
friend class ColladaMesh_SequenceNodeOfSequenceOfMeshDomain;
friend class ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle;
friend class ColladaMesh_SequenceNodeOfSequenceOfMesh;

};





// other Inline functions and methods (like "C++: function call" methods)


#endif
