// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ColladaMesh_SequenceOfMeshTriangle_HeaderFile
#define _ColladaMesh_SequenceOfMeshTriangle_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BaseSequence_HeaderFile
#include <TCollection_BaseSequence.hxx>
#endif
#ifndef _Handle_ColladaMesh_MeshTriangle_HeaderFile
#include <Handle_ColladaMesh_MeshTriangle.hxx>
#endif
#ifndef _Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_HeaderFile
#include <Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_NoSuchObject;
class Standard_OutOfRange;
class ColladaMesh_MeshTriangle;
class ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle;



class ColladaMesh_SequenceOfMeshTriangle  : public TCollection_BaseSequence {
public:

  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
      ColladaMesh_SequenceOfMeshTriangle();
  
  Standard_EXPORT     void Clear() ;
~ColladaMesh_SequenceOfMeshTriangle()
{
  Clear();
}
  
  Standard_EXPORT    const ColladaMesh_SequenceOfMeshTriangle& Assign(const ColladaMesh_SequenceOfMeshTriangle& Other) ;
   const ColladaMesh_SequenceOfMeshTriangle& operator =(const ColladaMesh_SequenceOfMeshTriangle& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT     void Append(const Handle(ColladaMesh_MeshTriangle)& T) ;
  
        void Append(ColladaMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT     void Prepend(const Handle(ColladaMesh_MeshTriangle)& T) ;
  
        void Prepend(ColladaMesh_SequenceOfMeshTriangle& S) ;
  
        void InsertBefore(const Standard_Integer Index,const Handle(ColladaMesh_MeshTriangle)& T) ;
  
        void InsertBefore(const Standard_Integer Index,ColladaMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT     void InsertAfter(const Standard_Integer Index,const Handle(ColladaMesh_MeshTriangle)& T) ;
  
        void InsertAfter(const Standard_Integer Index,ColladaMesh_SequenceOfMeshTriangle& S) ;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshTriangle& First() const;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshTriangle& Last() const;
  
        void Split(const Standard_Integer Index,ColladaMesh_SequenceOfMeshTriangle& Sub) ;
  
  Standard_EXPORT    const Handle_ColladaMesh_MeshTriangle& Value(const Standard_Integer Index) const;
   const Handle_ColladaMesh_MeshTriangle& operator()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Handle(ColladaMesh_MeshTriangle)& I) ;
  
  Standard_EXPORT     Handle_ColladaMesh_MeshTriangle& ChangeValue(const Standard_Integer Index) ;
    Handle_ColladaMesh_MeshTriangle& operator()(const Standard_Integer Index) 
{
  return ChangeValue(Index);
}
  
  Standard_EXPORT     void Remove(const Standard_Integer Index) ;
  
  Standard_EXPORT     void Remove(const Standard_Integer FromIndex,const Standard_Integer ToIndex) ;





protected:





private:

  
  Standard_EXPORT   ColladaMesh_SequenceOfMeshTriangle(const ColladaMesh_SequenceOfMeshTriangle& Other);




};

#define SeqItem Handle_ColladaMesh_MeshTriangle
#define SeqItem_hxx <ColladaMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshTriangle.hxx>

#include <TCollection_Sequence.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
