// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _DBC_VArrayOfExtCharacter_HeaderFile
#define _DBC_VArrayOfExtCharacter_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#include <DBC_BaseArray.hxx>
#include <Standard_ExtCharacter.hxx>
#include <Handle_DBC_VArrayNodeOfVArrayOfExtCharacter.hxx>
#include <Standard_Integer.hxx>
#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif
class Standard_NegativeValue;
class Standard_OutOfRange;
class Standard_DimensionMismatch;
class Standard_NullObject;
class DBC_VArrayNodeOfVArrayOfExtCharacter;
class DBC_VArrayTNodeOfVArrayOfExtCharacter;



Standard_EXPORT const Handle(Standard_Type)& STANDARD_TYPE(DBC_VArrayOfExtCharacter);


class DBC_VArrayOfExtCharacter  : public DBC_BaseArray {

public:
  void* operator new(size_t,void* anAddress) 
  {
    return anAddress;
  }
  void* operator new(size_t size) 
  {
    return Standard::Allocate(size); 
  }
  void  operator delete(void *anAddress) 
  {
    if (anAddress) Standard::Free((Standard_Address&)anAddress); 
  }

  
  Standard_EXPORT   DBC_VArrayOfExtCharacter();
  
  Standard_EXPORT   DBC_VArrayOfExtCharacter(const Standard_Integer Size);
  
  Standard_EXPORT   DBC_VArrayOfExtCharacter(const DBC_VArrayOfExtCharacter& Varray);
  
  Standard_EXPORT     void Resize(const Standard_Integer Size) ;
  
  Standard_EXPORT     void Assign(const DBC_VArrayOfExtCharacter& Other) ;
    void operator =(const DBC_VArrayOfExtCharacter& Other) 
{
  Assign(Other);
}
  
  Standard_EXPORT     void SetValue(const Standard_Integer Index,const Standard_ExtCharacter& Value) ;
  
  Standard_EXPORT     Standard_ExtCharacter& Value(const Standard_Integer Index) const;
    Standard_ExtCharacter& operator ()(const Standard_Integer Index) const
{
  return Value(Index);
}
  
  Standard_EXPORT     void Destroy() ;
~DBC_VArrayOfExtCharacter()
{
  Destroy();
}



protected:




private: 

#ifdef CSFDB
// DBC_VArray : field
//
#endif



};





// other Inline functions and methods (like "C++: function call" methods)


#endif
