// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Graphic3d_LevelOfTextureAnisotropy_HeaderFile
#define _Graphic3d_LevelOfTextureAnisotropy_HeaderFile

//! Type of the texture filter. <br>
//! Notice that for textures without mipmaps linear interpolation will be used instead of TOTF_BILINEAR and TOTF_TRILINEAR. <br>
enum Graphic3d_LevelOfTextureAnisotropy {
Graphic3d_LOTA_OFF,
Graphic3d_LOTA_FAST,
Graphic3d_LOTA_MIDDLE,
Graphic3d_LOTA_QUALITY
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
