// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PBRep_PolygonOnSurface_HeaderFile
#define _PBRep_PolygonOnSurface_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_PBRep_PolygonOnSurface_HeaderFile
#include <Handle_PBRep_PolygonOnSurface.hxx>
#endif

#include <Standard_Boolean.hxx>
#include <Handle_PGeom_Surface.hxx>
#include <Handle_PPoly_Polygon2D.hxx>
#include <PBRep_CurveRepresentation.hxx>
class PGeom_Surface;
class PPoly_Polygon2D;
class PTopLoc_Location;


class PBRep_PolygonOnSurface : public PBRep_CurveRepresentation {

public:

  
  Standard_EXPORT   PBRep_PolygonOnSurface(const Handle(PPoly_Polygon2D)& P,const Handle(PGeom_Surface)& S,const PTopLoc_Location& L);
  //! A   2D polygon  representation  in the  parametric <br>
//!          space of a surface. <br>
  Standard_EXPORT   virtual  Standard_Boolean IsPolygonOnSurface() const;
  
  Standard_EXPORT     Handle_PGeom_Surface Surface() const;
  
  Standard_EXPORT     Handle_PPoly_Polygon2D Polygon() const;

  PBRep_PolygonOnSurface( )
{
  
}
PBRep_PolygonOnSurface(const Storage_stCONSTclCOM& a) : PBRep_CurveRepresentation(a)
{
  
}
    Handle(PPoly_Polygon2D) _CSFDB_GetPBRep_PolygonOnSurfacemyPolygon2D() const { return myPolygon2D; }
    void _CSFDB_SetPBRep_PolygonOnSurfacemyPolygon2D(const Handle(PPoly_Polygon2D)& p) { myPolygon2D = p; }
    Handle(PGeom_Surface) _CSFDB_GetPBRep_PolygonOnSurfacemySurface() const { return mySurface; }
    void _CSFDB_SetPBRep_PolygonOnSurfacemySurface(const Handle(PGeom_Surface)& p) { mySurface = p; }



  DEFINE_STANDARD_RTTI(PBRep_PolygonOnSurface)

protected:




private: 


Handle_PPoly_Polygon2D myPolygon2D;
Handle_PGeom_Surface mySurface;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
