// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface_HeaderFile
#define _PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface_HeaderFile
#include <Handle_PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface.hxx>
#endif

#include <Standard_Address.hxx>
#include <Handle_PGeom_BoundedSurface.hxx>
#include <PStandard_ArrayNode.hxx>
class PGeom_BoundedSurface;
class PColPGeom_FieldOfHArray1OfBoundedSurface;
class PColPGeom_VArrayTNodeOfFieldOfHArray1OfBoundedSurface;


class PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface : public PStandard_ArrayNode {

public:

  
  Standard_EXPORT   PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface();
  
  Standard_EXPORT   PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface(const Handle(PGeom_BoundedSurface)& aValue);
  
  Standard_EXPORT     void SetValue(const Handle(PGeom_BoundedSurface)& aValue) ;
  
  Standard_EXPORT     Standard_Address Value() const;

PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface(const Storage_stCONSTclCOM& a) : PStandard_ArrayNode(a)
{
  
}
    Handle(PGeom_BoundedSurface) _CSFDB_GetPColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurfacemyValue() const { return myValue; }
    void _CSFDB_SetPColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurfacemyValue(const Handle(PGeom_BoundedSurface)& p) { myValue = p; }



  DEFINE_STANDARD_RTTI(PColPGeom_VArrayNodeOfFieldOfHArray1OfBoundedSurface)

protected:




private: 


Handle_PGeom_BoundedSurface myValue;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
