// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PTopoDS_TVertex1_HeaderFile
#define _PTopoDS_TVertex1_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_PTopoDS_TVertex1_HeaderFile
#include <Handle_PTopoDS_TVertex1.hxx>
#endif

#include <TopAbs_ShapeEnum.hxx>
#include <PTopoDS_TShape1.hxx>


class PTopoDS_TVertex1 : public PTopoDS_TShape1 {

public:

  
  Standard_EXPORT     TopAbs_ShapeEnum ShapeType() const;

PTopoDS_TVertex1(const Storage_stCONSTclCOM& a) : PTopoDS_TShape1(a)
{
  
}
  PTopoDS_TVertex1( )
{
  
}



  DEFINE_STANDARD_RTTI(PTopoDS_TVertex1)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
