// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _ColladaMesh_Mesh_HeaderFile
#include <ColladaMesh_Mesh.hxx>
#endif
#ifndef _ColladaMesh_SequenceOfMesh_HeaderFile
#include <ColladaMesh_SequenceOfMesh.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(ColladaMesh_SequenceNodeOfSequenceOfMesh)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(ColladaMesh_SequenceNodeOfSequenceOfMesh)


IMPLEMENT_DOWNCAST(ColladaMesh_SequenceNodeOfSequenceOfMesh,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(ColladaMesh_SequenceNodeOfSequenceOfMesh)


#define SeqItem Handle_ColladaMesh_Mesh
#define SeqItem_hxx <ColladaMesh_Mesh.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMesh.hxx>
#include <TCollection_SequenceNode.gxx>

