// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _ColladaMesh_MeshDomain_HeaderFile
#include <ColladaMesh_MeshDomain.hxx>
#endif
#ifndef _ColladaMesh_SequenceOfMeshDomain_HeaderFile
#include <ColladaMesh_SequenceOfMeshDomain.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(ColladaMesh_SequenceNodeOfSequenceOfMeshDomain)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(ColladaMesh_SequenceNodeOfSequenceOfMeshDomain)


IMPLEMENT_DOWNCAST(ColladaMesh_SequenceNodeOfSequenceOfMeshDomain,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(ColladaMesh_SequenceNodeOfSequenceOfMeshDomain)


#define SeqItem Handle_ColladaMesh_MeshDomain
#define SeqItem_hxx <ColladaMesh_MeshDomain.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshDomain.hxx>
#include <TCollection_SequenceNode.gxx>

