// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceOfMeshDomain.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _ColladaMesh_MeshDomain_HeaderFile
#include <ColladaMesh_MeshDomain.hxx>
#endif
#ifndef _ColladaMesh_SequenceNodeOfSequenceOfMeshDomain_HeaderFile
#include <ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#endif
 

#define SeqItem Handle_ColladaMesh_MeshDomain
#define SeqItem_hxx <ColladaMesh_MeshDomain.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshDomain.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshDomain
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshDomain_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshDomain
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshDomain.hxx>
#include <TCollection_Sequence.gxx>

