// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _ColladaMesh_MeshTriangle_HeaderFile
#include <ColladaMesh_MeshTriangle.hxx>
#endif
#ifndef _ColladaMesh_SequenceOfMeshTriangle_HeaderFile
#include <ColladaMesh_SequenceOfMeshTriangle.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle)


IMPLEMENT_DOWNCAST(ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle)


#define SeqItem Handle_ColladaMesh_MeshTriangle
#define SeqItem_hxx <ColladaMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshTriangle.hxx>
#include <TCollection_SequenceNode.gxx>

