// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceOfMeshTriangle.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _ColladaMesh_MeshTriangle_HeaderFile
#include <ColladaMesh_MeshTriangle.hxx>
#endif
#ifndef _ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_HeaderFile
#include <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#endif
 

#define SeqItem Handle_ColladaMesh_MeshTriangle
#define SeqItem_hxx <ColladaMesh_MeshTriangle.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMeshTriangle_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMeshTriangle
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMeshTriangle.hxx>
#include <TCollection_Sequence.gxx>

