// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ColladaMesh_SequenceOfMesh.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _ColladaMesh_Mesh_HeaderFile
#include <ColladaMesh_Mesh.hxx>
#endif
#ifndef _ColladaMesh_SequenceNodeOfSequenceOfMesh_HeaderFile
#include <ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>
#endif
 

#define SeqItem Handle_ColladaMesh_Mesh
#define SeqItem_hxx <ColladaMesh_Mesh.hxx>
#define TCollection_SequenceNode ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_hxx <ColladaMesh_SequenceNodeOfSequenceOfMesh.hxx>
#define Handle_TCollection_SequenceNode Handle_ColladaMesh_SequenceNodeOfSequenceOfMesh
#define TCollection_SequenceNode_Type_() ColladaMesh_SequenceNodeOfSequenceOfMesh_Type_()
#define TCollection_Sequence ColladaMesh_SequenceOfMesh
#define TCollection_Sequence_hxx <ColladaMesh_SequenceOfMesh.hxx>
#include <TCollection_Sequence.gxx>

